plugins {
    id 'com.github.johnrengelman.shadow'
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = file("src/main/resources/academy-fabric.accesswidener")
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation("net.fabricmc:fabric-loader:$rootProject.fabric_loader_version")
    modImplementation("net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version")
    modImplementation("dev.architectury:architectury-fabric:$rootProject.architectury_api_version")
    include(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:0.3.3"))
    implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:0.3.3"))
    include("com.madgag:animated-gif-lib:1.4")
    implementation("com.madgag:animated-gif-lib:1.4")

    modImplementation("com.cobblemon:fabric:1.7.0+1.21.1")
    modImplementation("net.fabricmc:fabric-language-kotlin:1.13.3+kotlin.2.1.21")

    modImplementation("maven.modrinth:jei:19.25.1.332")

    //modImplementation("io.wispforest:owo-sentinel:0.12.15.4+1.21")
    //modImplementation("io.wispforest:owo-lib:0.12.15.4+1.21")

    //modImplementation("maven.modrinth:cobblemon-myths-and-legends-sidemod:1.7.2")
    //modImplementation(project(":common").files("jars/toml4j-0.7.2.jar"))

    modImplementation("maven.modrinth:enhanced-celestials:6.0.2.4-fabric")
    modImplementation("maven.modrinth:corgilib:1.21.1-5.0.0.7-Fabric")
    modImplementation("maven.modrinth:data-anchor:2.0.0.12-fabric")

    modImplementation("maven.modrinth:eternal-starlight:0.5.1+1.21.1+fabric")

    modImplementation("software.bernie.geckolib:geckolib-fabric-1.21.1:4.7.5.1")

    modImplementation("maven.modrinth:fading-clouds:1.1.0")

    implementation(shadowBundle("com.squareup.okhttp3:okhttp:4.12.0"))

    modImplementation("dev.emi:trinkets:3.10.0")
    modImplementation("maven.modrinth:cardinal-components-api:6.1.2")

    //modImplementation("maven.modrinth:fancymenu:3.7.0-1.21.1-fabric")
    //modImplementation("maven.modrinth:konkrete:1.9.9-1.21-fabric")
    //modImplementation("maven.modrinth:melody:1.0.10-1.21-fabric")

    modImplementation("maven.modrinth:rad-gyms:1.7.0_0.3.1-stable")
    modImplementation("maven.modrinth:rctapi:3EKcU1cf")
    modImplementation("maven.modrinth:admiral:0.4.10+1.21.1+fabric")

    modImplementation("dev.ftb.mods:ftb-quests-fabric:2101.1.14")
    modImplementation("dev.ftb.mods:ftb-teams-fabric:2101.1.4")
    modImplementation("dev.ftb.mods:ftb-library-fabric:2101.1.19")
    modImplementation("dev.ftb.mods:ftb-essentials-fabric:2101.1.6")

    //modImplementation("maven.modrinth:cobblemon-alpha-project:1.1")

    modImplementation("maven.modrinth:bookshelf-lib:ckzM6Bhh")

    //modImplementation("maven.modrinth:lootables:0.1.4+1.21.1")
    //modImplementation("maven.modrinth:fzzy-config:0.7.2+1.21")
    //modImplementation("net.peanuuutz.tomlkt:tomlkt:0.5.0")

    modCompileOnly("dev.emi:emi-fabric:1.1.22+1.21.1:api")
    modLocalRuntime("dev.emi:emi-fabric:1.1.22+1.21.1")

    modImplementation("maven.modrinth:sophisticated-storage-(unofficial-fabric-port):1.21.1-1.3.7.9.139")
    modImplementation("maven.modrinth:sophisticated-core-(unofficial-fabric-port):1.21.1-1.2.9.21.168")



    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    atAccessWideners.add "academy-common.accesswidener"
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Abes-Hutt/StarAcademyMod")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
    publications {
        gpr(MavenPublication) {
            groupId = rootProject.maven_group
            artifactId = rootProject.archives_name.toLowerCase()
            version = "mc${rootProject.minecraft_version}-v${rootProject.mod_version}${getBuildNumber()}-${project.name}"
            from components.java
        }
    }
}

tasks.register('printVersion') {
    println "mc$rootProject.minecraft_version-v$rootProject.mod_version${getBuildNumber()}-fabric"
}

static def getBuildNumber() {
    if(System.getenv("GITHUB_RUN_NUMBER") != null) {
        return "+build." + System.getenv("GITHUB_RUN_NUMBER").toString()
    }

    return ""
}
