plugins {
    id 'com.github.johnrengelman.shadow'
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/academy-common.accesswidener")
}

dependencies {
    modCompileOnly("net.fabricmc:fabric-loader:$rootProject.fabric_loader_version")
    modCompileOnly("net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version")
    modCompileOnly("dev.architectury:architectury:$rootProject.architectury_api_version")
    implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:0.3.3"))
    compileOnly("com.madgag:animated-gif-lib:1.4")

    modCompileOnly("com.cobblemon:mod:1.7.0+1.21.1")
    modCompileOnly(files("jars/molang-1.1.18.jar"))

    modCompileOnly("maven.modrinth:jei:19.25.1.332")

    modCompileOnly("io.wispforest:owo-sentinel:0.12.15.4+1.21")
    modCompileOnly(annotationProcessor("io.wispforest:owo-lib:0.12.15.4+1.21"))

    modCompileOnly("maven.modrinth:item-obliterator:3.1.1")

    modCompileOnly("maven.modrinth:enhanced-celestials:6.0.2.4-fabric")
    modCompileOnly("maven.modrinth:corgilib:1.21.1-5.0.0.7-Fabric")
    modCompileOnly("maven.modrinth:data-anchor:2.0.0.12-fabric")

    modCompileOnly("software.bernie.geckolib:geckolib-fabric-1.21.1:4.7.5.1")

    modCompileOnly("maven.modrinth:eternal-starlight:0.5.1+1.21.1+fabric")

    modCompileOnly("maven.modrinth:itemzoomer:1.1.0-1.21.1")

    modCompileOnly("maven.modrinth:journeymap:WvOAHk8e")

    modCompileOnly("maven.modrinth:modernfix:5.24.3+mc1.21.1")

    modCompileOnly("maven.modrinth:displayed:1.0.2-fabric-1.21.1")

    modCompileOnly("maven.modrinth:cobblemon-myths-and-legends-sidemod:1.7.2")

    modCompileOnly("maven.modrinth:rad-gyms:1.7.0_0.3.1-stable")
    modCompileOnly("maven.modrinth:rctapi:3EKcU1cf")
    modCompileOnly("maven.modrinth:admiral:0.4.10+1.21.1+fabric")

    modCompileOnly("maven.modrinth:fading-clouds:1.1.0")

    modCompileOnly("maven.modrinth:shutters:2.1.2")

    modCompileOnly("com.squareup.okhttp3:okhttp:4.12.0")

    modCompileOnly("dev.emi:trinkets:3.10.0")
    modCompileOnly("maven.modrinth:cardinal-components-api:6.1.2")

    modCompileOnly("maven.modrinth:fancymenu:3.7.0-1.21.1-fabric")
    modCompileOnly("maven.modrinth:konkrete:1.9.9-1.21-fabric")
    modCompileOnly("maven.modrinth:melody:1.0.10-1.21-fabric")

    modCompileOnly("maven.modrinth:cobblemon-alpha-project:1.1")

    modCompileOnly("dev.ftb.mods:ftb-quests:2101.1.14")
    modCompileOnly("dev.ftb.mods:ftb-teams:2101.1.4")
    modCompileOnly("dev.ftb.mods:ftb-library:2101.1.19")
    modCompileOnly("dev.ftb.mods:ftb-essentials:2101.1.6")

    modCompileOnly(files("jars/UltraBeasts-1.0.1.jar"))

    modCompileOnly("maven.modrinth:extraquests:xyNKgwgq")

    modCompileOnly("maven.modrinth:cobblemon-alpha-project:1.1")

    modCompileOnly("maven.modrinth:bookshelf-lib:ckzM6Bhh")

    modCompileOnly("maven.modrinth:cobblemon-mega-showdown:10.0.7-release-fabric")

    modCompileOnly("maven.modrinth:gliding:1.0.1")

    modCompileOnly("dev.emi:emi-xplat-intermediary:1.1.22+1.21.1:api")

    modCompileOnly("maven.modrinth:lootables:0.1.4+1.21.1")

    modCompileOnly("maven.modrinth:cobblemon-mass-outbreaks:1.0.0-1.21.1-fabric")

    modCompileOnly("maven.modrinth:moonrise-opt:5IV5gcdA")
    modCompileOnly("maven.modrinth:sophisticated-storage-(unofficial-fabric-port):1.21.1-1.3.7.9.139")
    modCompileOnly("maven.modrinth:sophisticated-core-(unofficial-fabric-port):1.21.1-1.2.9.21.168")

    modCompileOnly(files("jars/xercapaint-1.21.1-1.0.1.jar"))

    modCompileOnly("maven.modrinth:cobblemon-scoremons:3.1")
}
